# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolygonClusterReducer
                                 A QGIS plugin
 This plugin removes polygons from the cluster, based on the user parameters.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-15
        copyright            : (C) 2018 by Zoran Petrović / Zoran-Software.com
        email                : zoran@zoran-software.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PolygonClusterReducer class from file PolygonClusterReducer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .polygon_cluster_reducer import PolygonClusterReducer
    return PolygonClusterReducer(iface)
